In [32]:
import pandas as pd
import numpy as np

In [3]:
df=pd.DataFrame({'a': range(1, 11, 1), 'b': range(11, 21, 1)}, index=pd.date_range('2023-01-01', '2023-01-10', freq='D'))

In [4]:
df

             a   b
2023-01-01   1  11
2023-01-02   2  12
2023-01-03   3  13
2023-01-04   4  14
2023-01-05   5  15
2023-01-06   6  16
2023-01-07   7  17
2023-01-08   8  18
2023-01-09   9  19
2023-01-10  10  20

In [40]:
df.resample('2D', closed='right', label='right', offset='1D').apply(
   (np.max, np.min)
)

/tmp/ipykernel_741360/2523788217.py:1: FutureWarning: The provided callable <function max at 0x72c262698b80> is currently using SeriesGroupBy.max. In a future version of pandas, the provided callable will be used directly. To keep current behavior pass the string "max" instead.
  df.resample('2D', closed='right', label='right', offset='1D').apply(
/tmp/ipykernel_741360/2523788217.py:1: FutureWarning: The provided callable <function min at 0x72c262698ca0> is currently using SeriesGroupBy.min. In a future version of pandas, the provided callable will be used directly. To keep current behavior pass the string "min" instead.
  df.resample('2D', closed='right', label='right', offset='1D').apply(

             a       b
           max min max min
2023-01-02   2   1  12  11
2023-01-04   4   3  14  13
2023-01-06   6   5  16  15
2023-01-08   8   7  18  17
2023-01-10  10   9  20  19

In [19]:
df.resample('2D', closed='right', label='right', offset='1D').agg(
    lambda x: pd.Series({'a': x['a'].sum(), 'b_mean': x['b'].mean(), 'b_max': x['b'].max()})
)

               a  b_mean  b_max
2023-01-02   3.0    11.5   12.0
2023-01-04   7.0    13.5   14.0
2023-01-06  11.0    15.5   16.0
2023-01-08  15.0    17.5   18.0
2023-01-10  19.0    19.5   20.0

In [ ]:
df.rolling(window=3, closed='both', center=True, ).agg(
    {'a': 'sum', 'b': 'mean'}
)

               a     b
2023-01-01   NaN   NaN
2023-01-02   6.0  12.0
2023-01-03  10.0  12.5
2023-01-04  14.0  13.5
2023-01-05  18.0  14.5
2023-01-06  22.0  15.5
2023-01-07  26.0  16.5
2023-01-08  30.0  17.5
2023-01-09  34.0  18.5
2023-01-10  27.0  19.0

In [47]:
df.shift(1, freq='D')

             a   b
2023-01-02   1  11
2023-01-03   2  12
2023-01-04   3  13
2023-01-05   4  14
2023-01-06   5  15
2023-01-07   6  16
2023-01-08   7  17
2023-01-09   8  18
2023-01-10   9  19
2023-01-11  10  20

In [20]:
df1 = df.copy()
df1['c'] = ['x', 'y'] * 5
df1

             a   b  c
2023-01-01   1  11  x
2023-01-02   2  12  y
2023-01-03   3  13  x
2023-01-04   4  14  y
2023-01-05   5  15  x
2023-01-06   6  16  y
2023-01-07   7  17  x
2023-01-08   8  18  y
2023-01-09   9  19  x
2023-01-10  10  20  y

In [54]:
df1.groupby('c').filter(
    lambda x: x['a'].sum() > 25,
    dropna=False
)

               a     b    c
2023-01-01   NaN   NaN  NaN
2023-01-02   2.0  12.0    y
2023-01-03   NaN   NaN  NaN
2023-01-04   4.0  14.0    y
2023-01-05   NaN   NaN  NaN
2023-01-06   6.0  16.0    y
2023-01-07   NaN   NaN  NaN
2023-01-08   8.0  18.0    y
2023-01-09   NaN   NaN  NaN
2023-01-10  10.0  20.0    y

In [55]:
df1.groupby('c').apply(
    lambda x: pd.DataFrame({
        'a': -1*x['a']
    })
)

/tmp/ipykernel_741360/913346061.py:1: FutureWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  df1.groupby('c').apply(

               a
c
x 2023-01-01  -1
  2023-01-03  -3
  2023-01-05  -5
  2023-01-07  -7
  2023-01-09  -9
y 2023-01-02  -2
  2023-01-04  -4
  2023-01-06  -6
  2023-01-08  -8
  2023-01-10 -10

In [57]:
df1.head(1)

            a   b  c
2023-01-01  1  11  x

In [73]:
df1.groupby('c', group_keys=True).apply(lambda x: x)

/tmp/ipykernel_741360/2050792051.py:1: FutureWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  df1.groupby('c', group_keys=True).apply(lambda x: x)

               a   b  c
c
x 2023-01-01   1  11  x
  2023-01-03   3  13  x
  2023-01-05   5  15  x
  2023-01-07   7  17  x
  2023-01-09   9  19  x
y 2023-01-02   2  12  y
  2023-01-04   4  14  y
  2023-01-06   6  16  y
  2023-01-08   8  18  y
  2023-01-10  10  20  y

In [ ]:
grouped.get_group('x')

In [ ]:
df.groupby('c').apply(lambda x: pd.DataFrame({'a': [x['a'].max(), x['a'].min()], 'b': [x['b'].max(), x['b'].min()]}, index=['max', 'min']))

KeyError: 'b'

In [54]:
df.apply(lambda x: x.idxmax())

a    c
b    c
c    b
dtype: object

In [25]:
ds.to_frame()

   b
0  1
1  2
2  3

In [26]:
del df['a']

In [27]:
df

   b
a  4
b  5
c  6

In [28]:
df.pop('b')

a    4
b    5
c    6
Name: b, dtype: int64

In [29]:
df

Empty DataFrame
Columns: []
Index: [a, b, c]

In [30]:
df['c'] = [7,8,9]
df

   c
a  7
b  8
c  9

In [31]:
df.insert(0, 'd', [4,5,6])

In [32]:
df

   d  c
a  4  7
b  5  8
c  6  9

In [33]:
df.assign(e=df['c'])

   d  c  e
a  4  7  7
b  5  8  8
c  6  9  9

In [34]:
df

   d  c
a  4  7
b  5  8
c  6  9

In [35]:
df.assign(x=lambda x: x['c'], y=lambda x: x['d'])

   d  c  x  y
a  4  7  7  4
b  5  8  8  5
c  6  9  9  6

In [36]:
df.empty

False

In [37]:
df.rename(columns={'c': 'c1'}, index={'a':'a1'})

    d  c1
a1  4   7
b   5   8
c   6   9

In [40]:
df.iloc[:2, :2]

   d  c
a  4  7
b  5  8

In [42]:
df.iat[0, 0]=9

In [43]:
df

   d  c
a  9  7
b  5  8
c  6  9

In [45]:
df.loc['a':'b', 'd':'c']

   d  c
a  9  7
b  5  8

In [51]:
df.iloc[df.index.get_indexer(['a']), df.columns.get_indexer(['d'])]

   d
a  9

In [52]:
df.columns.get_level_values(0)

Index(['d', 'c'], dtype='object')

In [55]:
df.loc[:, ('c',)]

   c
a  7
b  8
c  9

In [56]:
df.convert_dtypes()

   d  c
a  9  7
b  5  8
c  6  9

In [57]:
df.select_dtypes(include=['number'], exclude=['string'])

   d  c
a  9  7
b  5  8
c  6  9

In [58]:
df.value_counts()

d  c
5  8    1
6  9    1
9  7    1
Name: count, dtype: int64

In [62]:
df.sub(df['d'], axis=0)

   d  c
a  0 -2
b  0  3
c  0  3

In [63]:
df.equals(df.copy())

True

In [64]:
import numpy as np
df.iat[0,0]=np.nan

In [68]:
df1=df.copy()
df1.fillna(3, inplace=True)

In [67]:
df.equals(df.copy())

True

In [69]:
df.combine_first(df1)

     d  c
a  3.0  7
b  5.0  8
c  6.0  9

In [70]:
df

     d  c
a  NaN  7
b  5.0  8
c  6.0  9

In [1]:
df.apply(lambda x: x.idxmax(), axis=1)

NameError: name 'df' is not defined

In [88]:
df.apply({'d': "mean", "c": "sum"})

d     5.5
c    24.0
dtype: float64

In [81]:
df1.columns

AttributeError: 'Series' object has no attribute 'columns'